verison: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dol-14c-{{ checksum "DOL.WHD.Section14c.Web/package.json" }}
      - restore_cache:
          key: dol-14c-hardsource
      - run:
          name: install dependencies
          command: cd DOL.WHD.Section14c.Web && npm install
      - save_cache:
          key: dol-14c-{{ checksum "DOL.WHD.Section14c.Web/package.json" }}
          paths:
            - DOL.WHD.Section14c.Web/node_modules
      - save_cache:
          key: dol-14c-hardsource
          paths:
            - DOL.WHD.Section14c.Web/node_modules/.cache/hard-source
      - run:
          name: run the tests
          command: cd DOL.WHD.Section14c.Web && npm test
      - run:
          name: report coverage
          when: always
          command: cd DOL.WHD.Section14c.Web && bash <(curl -s https://codecov.io/bash)
